### PR TITLE
Updating LHC to include recent fixes

### PR DESCRIPTION
**Pull request by tculotta**

### CODE REVIEW

**Comment by tculotta** [comment]
Moved back to a previously tested commit that still has the needed fixes

**Comment by jplafonta** [comment]
any reason to not jump to HEAD?
=

---
In reply to: [1059521052](https://github.com/PlayFab/PlayFabCoreCSdk/pull/8#issuecomment-1059521052) [](http://example.com/codeflow?ancestors=1059521052,1059521052)

**Comment by tculotta** [comment]
> 

I wasn't actually sure if there was in-progress stuff in HEAD after trying it. Once the current LHC PR gets merged though, I can move it there

**Review by jplafonta — APPROVED** [review]
:shipit:

**Pull request merged**
